# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-30 16:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('date_comment_created', models.DateTimeField(auto_now_add=True)),
                ('date_comment_updated', models.DateTimeField(auto_now=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_contributor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_name', models.CharField(max_length=120)),
                ('issue_description', models.TextField()),
                ('date_issue_created', models.DateTimeField(auto_now_add=True)),
                ('date_issue_updated', models.DateTimeField(auto_now=True)),
                ('is_issue_solved', models.BooleanField(default=False)),
                ('date_issue_solved', models.DateTimeField(blank=True, null=True)),
                ('issue_upvotes', models.IntegerField(default=0)),
                ('tag', models.CharField(blank=True, max_length=30, null=True)),
                ('issue_image', models.ImageField(blank=True, null=True, upload_to='issue_images')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('issue_type', models.CharField(choices=[('BUG', 'bug'), ('FEATURE', 'feature')], default='BUG', max_length=9)),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='TODO', max_length=7)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_issue', to='issues.Issue'),
        ),
    ]
